external_components:
  - source:
      type: local
      path: components/

  #- source: github://shadow578/esphome_sda5708@main
  #  components: [sda5708]

esphome:
  name: sdadisp-test

esp32:
  board: esp32-s3-devkitc1-n16r8
  cpu_frequency: 240MHZ
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "SDA-Test Fallback Hotspot"
    password: ""

captive_portal:

web_server:

button:
  - platform: restart
    name: "Restart"

  - platform: template
    name: "Brightness +"
    on_press:
      then:
        - sda5708.set_brightness:
            brightness: !lambda "return id(sda).get_brightness() + 1;"

  - platform: template
    name: "Brightness -"
    on_press:
      then:
        - sda5708.set_brightness:
            brightness: !lambda "return id(sda).get_brightness() - 1;"

time:
  - platform: sntp
    id: sntp_time

text:
  - platform: template
    id: display_text
    name: "Text"
    optimistic: true
    mode: text

display:
  - platform: sda5708
    id: sda
    data_pin: GPIO3
    clock_pin: GPIO13
    load_pin: GPIO12
    reset_pin: GPIO14
    brightness: 5
    lambda: |-
      auto now = id(sntp_time).now();
      auto userText = id(display_text).state;

      if (userText.length() > 0) {
        it.print(userText.c_str());

        it.print(0, "\2"); // custom glyph test
      } else {
        it.strftime("%H\3%M\3%S", now);
      }
    custom_glyphs:
      - char: 'H'
        glyph:
          - "     "
          - " # # "
          - "     "
          - "     "
          - "#   #"
          - " ### "
          - "     "
      - char: '\2'
        glyph:
          - "     "
          - " # # "
          - "#####"
          - "#####"
          - " ### "
          - "  #  "
          - "     "
      - char: '\3'
        glyph:
          - "     "
          - "  #  "
          - " ### "
          - "## ##"
          - " ### "
          - "  #  "
          - "     "
      - char: 'C'
        glyph:
          - "##   "
          - "##   "
          - "  ## "
          - " #  #"
          - " #   "
          - " #  #"
          - "  ## "